#!/bin/sh
#
# xxxx      This shell script takes care of starting and stopping
#             standalone xxxx.
#		Las lineas siguientes aunque son comentarios las utilizan
#		otros programas y son necesarias.
# chkconfig: - 60 50
# description: Descripcion del servicio. Esta linea debe existir.
# processname: xxxx
# config: /etc/xxxx.conf

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0

#Valor de retorno, utilizado para indicar si hay error.
RETVAL=0 
prog="xxxxd"

start() {
        # Start daemons.
        echo $"Starting $prog: "
        #Comando para arrancar el servicio, por ejemplo /bin/xxxx o usar
        # la funcion daemon definida en /etc/rc.d/init.d/functions
        RETVAL=$?
        [ $RETVAL -eq 0 ] && {
        	touch /var/lock/subsys/$prog
        	success $"$prog" 
        } 
        echo
        return $RETVAL
}

stop() {
        # Stop daemons.
        echo $"Shutting down $prog: "
        killproc $prog
        RETVAL=$?
        [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$prog
        echo
        return $RETVAL
}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        RETVAL=$?
        ;;
  condrestart)
        if [ -f /var/lock/subsys/$prog ]; then
            stop
            start
            RETVAL=$?
        fi
        ;;
  status)
        status $prog
        RETVAL=$?
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|condrestart|status}"
        exit 1
esac

exit $RETVAL
