#!/bin/sh
#
# reader      This shell script takes care of starting and stopping
#             the bookReader.
# chkconfig: 2345 90 90
# description: Service which convert a physical book (photos) to PDF.
# processname: reader
# config: /etc/reader.conf

# Source function library.
. /etc/rc.d/init.d/functions

#Source the functions library.
FOLDER_1=""
FOLDER_2=""

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0

#Variable uses to indicate if an error occurs.
RETVAL=0 
prog="readerd"

start() {
        # Start daemons.
        echo $"Starting $prog: "
        #Run the service
        RETVAL=$?
        [ $RETVAL -eq 0 ] && {
        	touch /var/lock/subsys/$prog
        	success $"$prog"
        } 
        return $RETVAL
}

stop() {
        # Stop daemons.
        echo $"Shutting down $prog: "
        killproc $prog
        RETVAL=$?
        [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$prog
        echo "Parando el servicio"
        return $RETVAL
}

# See how we were called.
case "$1" in
  start)
        start
        echo "Iniciando el servicio"
        #TODO: Cuando se inicie que llame al script y pasandole las carpetas FOLDER_X:
        ./home/dit/prueba.sh &
	;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        RETVAL=$?
        ;;
  condrestart)
        if [ -f /var/lock/subsys/$prog ]; then
            stop
            start
            RETVAL=$?
        fi
        ;;
  status)
        status $prog
        RETVAL=$?
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|condrestart|status}"
        exit 1
esac

exit $RETVAL
